POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL/Models/Login.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel.DataAnnotations;

namespace POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL.Models
{
    public class Login
    {
        [Display(Name = "Nombre del usuario")]
        [Required]
        public string Username { get; set; }

        [Display(Name = "Clave del usuario")]
        [Required]
        public string Password { get; set; }
    }
}

POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL/Models/usp_listar_policias.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL.Models
{
    public class usp_listar_policias
    {
        public string CODPOL { get; set; }
        public string NOMPOL { get; set; }
    }
}

POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL/Models/usp_papeletas_por_anio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL.Models
{
    public class usp_papeletas_por_anio
    {
        public int NROPAP { get; set; }
        public DateTime PAPFECHA { get; set; }
        public string NOMPRO { get; set; }
        public string NROPLA { get; set; }
        public string CODINF { get; set; }
    }
}

POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL/Models/usp_papeletas_por_policia_anio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL.Models
{
    public class usp_papeletas_por_policia_anio
    {
        public int NROPAP { get; set; }
        public DateTime PAPFECHA { get; set; }
        public string NOMPRO { get; set; }
        public string NROPLA { get; set; }
        public string CODINF { get; set; }
    }
}

POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL.Controllers
{
    public class LoginController : Controller
    {
        static string localUsername = "CIBER";
        static string localPassword = "T4CM2021";

        public ActionResult Login(string message = "")
        {
            ViewBag.MESSAGE = message;
            return View();
        }

        [HttpPost]
        public ActionResult Login(FormCollection collection)
        {

            String username = collection.Get("Username");
            String password = collection.Get("Password");

            if (!(username == localUsername && password == localPassword))
            {
                return Login("Error Usuario y/o Clave son Incorrectas");
            }

            return RedirectToAction("PapeletasPorAnio", "PREGUNTA2");
        }
    }
}

POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL/Controllers/PREGUNTA2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL.Controllers
{
    public class PREGUNTA2Controller : Controller
    {
        Papeletas_DAO papeletasDao = new Papeletas_DAO();

        public ActionResult PapeletasPorAnio(int anio = 0)
        {
            var list = papeletasDao.PapeletasPorAnio(anio);

            ViewBag.ANIO = anio;

            return View(list);
        }
    }
}

POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL/Controllers/PREGUNTA3Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL.Controllers
{
    public class PREGUNTA3Controller : Controller
    {
        Policia_DAO policiaDao = new Policia_DAO();
        Papeletas_DAO papeletasDao = new Papeletas_DAO();

        public ActionResult PapeletasPorPoliciaAnio(string codipol = "", int anio = 0)
        {
            var listaPapeletas = papeletasDao.PapeletasPorPoliciaAnio(codipol, anio);

            ViewBag.POLICIAS = new SelectList(
                policiaDao.Policias(),
                "codpol",
                "nompol"
                );

            ViewBag.ANIO = anio;

            return View(listaPapeletas);
        }
    }
}

POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL/Views/Login/Login.cshtml
@model POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL.Models.Login

@{
    ViewBag.Title = "Iniciar Sesión";
}

<div class="container">
  <div class="row">
    <div class="col-xs-12">
        <div class="panel">
            @using (Html.BeginForm()) 
            {
                @Html.AntiForgeryToken()

                <div class="panel-heading text-center">
                    <h4>Iniciar Sesión</h4>
                    <hr />
                </div>

                <div class="panel-body col-md-offset-3">
                    <div class="form-horizontal">

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Username,new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.PasswordFor(model => model.Password, new {  @class = "form-control"  })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Aceptar" class="btn btn-success" />
                                <a class="btn btn-warning" href="#">Cancelar</a>
                            </div>
                        </div>
                        
                        @{
                            if (!string.IsNullOrEmpty(ViewBag.MESSAGE))
                            {
                                <div class="alert alert-danger j-alert">@ViewBag.MESSAGE</div>
                            }
                        }
                    </div>
                </div>
            }
        </div>
    </div>
  </div>
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL/Views/PREGUNTA2/PapeletasPorAnio.cshtml
@model IEnumerable<POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL.Models.usp_papeletas_por_anio>

@{
    ViewBag.Title = "Papeletas por año";
}

<h2>Papeletas Por Año</h2>

@using (Html.BeginForm())
{

    <p>
        Ingrese un año : <input type="text" name="anio" value="@ViewBag.ANIO" class="form-control" style="display: inline-block !important;" />

        <input type="submit" value="Consultar" class="btn btn-default" />
    </p>
}

<p>
    @Html.ActionLink("Ir a lista de papeletas por policía y año ", "PapeletasPorPoliciaAnio", "PREGUNTA3")
</p>

<div class="table-responsive">
    <table class="table table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NROPAP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PAPFECHA)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NOMPRO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NROPLA)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CODINF)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NROPAP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PAPFECHA)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NOMPRO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NROPLA)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CODINF)
                </td>
            </tr>
        }
    </table>
</div>

POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL/Views/PREGUNTA3/PapeletasPorPoliciaAnio.cshtml
@model IEnumerable<POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL.Models.usp_papeletas_por_policia_anio>

@{
    ViewBag.Title = "PapeletasPorPoliciaAnio";
}

<h2>Papeletas por policía y año</h2>

@using (Html.BeginForm())
{
<p>
    Seleccione policía : @Html.DropDownList("codipol", (SelectList)ViewBag.POLICIAS, new { @class = "form-control", @style = "display: inline-block" })

    <br /> <br />
    
    Ingrese un año : <input type="text" name="anio" value="@ViewBag.ANIO" class="form-control" style="display: inline-block !important;" />

    <input type="submit" value="Consultar" class="btn btn-default" />
</p>
}


<p>
    @Html.ActionLink("Ir a lista de papeletas por año ", "PapeletasPorAnio", "PREGUNTA2")
</p>

<div class="table-responsive">
    <table class="table table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NROPAP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PAPFECHA)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NOMPRO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NROPLA)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CODINF)
            </th>
        </tr>

        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NROPAP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PAPFECHA)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NOMPRO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NROPLA)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CODINF)
                </td>
            </tr>
        }
    </table>
</div>

POO2_CASO1_ROBLES_COLONIA_JOSE_MANUEL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Transito 2018", "Login", "Login", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year - José Robles Colonia - Todos los derechos reservados</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>